# Generated by Django 4.2.15 on 2024-08-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Faces",
            fields=[
                ("face_id", models.AutoField(primary_key=True, serialize=False)),
                ("face_data", models.BinaryField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "faces",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="VideoUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video_file",
                    models.FileField(
                        upload_to="C:\\class1\\final_project\\DA35-Final-Minions-LOCKERs\\Lockers\\media"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
