# Generated by Django 4.2.15 on 2024-08-21 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("faces", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="VideoUpload",
        ),
    ]
