# Generated by Django 4.2.15 on 2024-08-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faces", "0003_delete_videoupload"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faces",
            name="face_data",
        ),
        migrations.AddField(
            model_name="faces",
            name="face_data_1",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="faces",
            name="face_data_10",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="faces",
            name="face_data_11",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="faces",
            name="face_data_12",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="faces",
            name="face_data_13",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="faces",
            name="face_data_14",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="faces",
            name="face_data_15",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="faces",
            name="face_data_16",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="faces",
            name="face_data_17",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="faces",
            name="face_data_2",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="faces",
            name="face_data_3",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="faces",
            name="face_data_4",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="faces",
            name="face_data_5",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="faces",
            name="face_data_6",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="faces",
            name="face_data_7",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="faces",
            name="face_data_8",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="faces",
            name="face_data_9",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
