# Generated by Django 4.2.15 on 2024-08-24 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payments",
            name="card_cvc",
        ),
        migrations.RemoveField(
            model_name="payments",
            name="card_expiry",
        ),
        migrations.RemoveField(
            model_name="payments",
            name="card_number",
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                ("card_id", models.AutoField(primary_key=True, serialize=False)),
                ("card_number", models.CharField(max_length=16)),
                ("card_expiry", models.CharField(max_length=5)),
                ("card_cvc", models.CharField(max_length=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "Card",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="payments",
            name="card",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payments.card",
            ),
        ),
    ]
