# Generated by Django 4.2.15 on 2024-08-24 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "payments",
            "0002_remove_payments_card_cvc_remove_payments_card_expiry_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payments",
            name="payment_method",
        ),
    ]
